### PR TITLE
Cmake cleanup

### PR DESCRIPTION
**Pull request by bcampbell**
I've done a whole bunch more cmake changes. It's starting to shape up properly now, so I'm happy for it to be merged in again.

Highlights:
- the libraries (IL/ILU/ILUT) are now handled by self-contained Cmakelist files, so the top-level project is just a holder for DevIL as a whole, rather than handling all the configuration.
- I've revamped the pkg-config support and included it in the install step (it's not 100%, but it works)
- removed a whole bunch of automake/eclipse/msvc build files, in favour of using cmake as the One True Build System (tm).

### CODE REVIEW

**Comment by DentonW** [comment]
Thanks for all your hard work on this. I need to spend some time trying this out on my system soon.

**Comment by DentonW** [comment]
Would it be possible to get CMake to create Visual Studio projects that output a DevIL.dll and DevIL.lib instead of IL.dll and IL.lib?

**Comment by bcampbell** [comment]
I _think_ it's easy enough, albeit a tad messier. I don't have a windows box handy to try it on right now, but if you want to give it a go, I think there are about two or three places in the cmake file you need to patch up. Look for lines like:
```
add_library( IL ... )
target_link_libraries(IL ...)

```
...and replace the `IL` with `${DevIL_libname}` or similar. Then add a `set( DevIL_libname IL)` near the top, with an additional `set( DevIL_libname DevIL)` in a win32-only section. Repeat for ILU and ILUT.

The rationale for using the IL name is that most of the unix-y systems have package it as such (I checked debian, ubuntu, fedora and arch linux, and  homebrew on the mac). Historical reasons I guess.

**Comment by DentonW** [comment]
I've been playing with CMake today for the first time, and it looks like I have that and some other issues fixed under Visual Studio. I need to test it out under Linux before I commit, in case I broke something.

**Comment by bcampbell** [comment]
Feel free to push up a branch with those changes for testing - I can give it a whirl for you on Linux and Mac.

**Comment by DentonW** [comment]
It should be updated. I may need to make some other changes, but it's getting into a more usable state now.

**Pull request merged**
