### PR TITLE
Fix not loading valid pngs but invalid ones.

### PR DESCRIPTION
**Pull request by max96at**
Good thing I was trying to load pngs with DevIL, otherwise this error would've probably gone unnoticed for quite a while....

### CODE REVIEW

**Comment by Ang3lus** [comment]
Hit this bug today, hoping this will be be merged soon.

**Comment by max96at** [comment]
Meanwhile you could use my fork, but yeah getting this merged would be nice...

**Comment by bcampbell** [comment]
Just to confirm - I stumbled across this issue too. Recommend merging!

**Comment by DentonW** [comment]
I'm obviously way late to this, but this fix is in the current codebase now. Thanks for finding this!

**Pull request closed without merging**
